export const enum MimeTypeEnum {
  image = 'image/*',
  audio = 'audio/*',
  video = 'video/*',
  jpg = 'image/jpg',
  jpeg = 'image/jpeg',
  png = 'image/png',
  gif = 'image/gif',
  bmp = 'image/bmp',
  pdf = 'application/pdf',
  msword = 'application/msword',
  odt = 'application/odt',
  txt = 'text/plain',
  xls = 'application/excel',
  ppt = 'application/ppt',
  dxf = 'application/dxf',
  mp3 = 'audio/mp3',
  wav = 'audio/wav',
  mp4 = 'video/mp4',
  mpeg = 'video/mpeg',
  zip = 'application/zip',
}
