import { DataRuntimeStateInterface } from './data-runtime/state';
import { DataPropertyStateInterface } from './data-property/state';
import { DataContactStateInterface } from './data-contact/state';
import { UiSearchlistStateInterface } from './ui-searchlist/state';
import { UiPropertyStateInterface } from './ui-property/state';
import { DataSearchlistStateInterface } from './data-searchlist/state';
import { DataAutocompleteStateInterface } from './data-autocomplete/state';
import { UiAutocompleteStateInterface } from './ui-autocomplete/state';
import { UiContactStateInterface } from './ui-contact/state';
import { DataMatchingGroupStateInterface } from './data-matching-group/state';
import { UiMatchingGroupStateInterface } from './ui-matching-group/state';
import { DataPromotionStateInterface } from './data-promotion/state';
import { UiPromotionStateInterface } from './ui-promotion/state';
import { DataEmailStateInterface } from './data-email/state';
import { UiReportingStateInterface } from './ui-reporting/state';
import { DataReportingStateInterface } from './data-reporting/state';
import { UiUserStateInterface } from './ui-user/state';
import { DataTaskStateInterface } from './data-task/state';
import { UiTaskStateInterface } from './ui-task/state';
import { DataHistoryStateInterface } from './data-history/state';
import { UiHistoryStateInterface } from './ui-history/state';
import { DataMatchingStateInterface } from './data-matching/state';
import { UiMatchingStateInterface } from './ui-matching/state';
import { DataSectorStateInterface } from './data-sector/state';
import { UiSectorStateInterface } from './ui-sector/state';
import { DataReportStateInterface } from './data-report/state';
import { UiReportStateInterface } from './ui-report/state';
import { UiMarketingExpenseStateInterface } from './ui-marketing-expense/state';
import { UiEmailStateInterface } from './ui-email/state';
import { UiPageStateInterface } from './ui-page/state';
import { DataMarketingExpenseStateInterface } from './data-marketing-expense/state';
import { DataPortalStateInterface } from './data-portal/state';
import { UiPortalStateInterface } from './ui-portal/state';
import { DataDeviceStateInterface } from './data-device/state';
import { UiDeviceStateInterface } from './ui-device/state';
import { UiFormStateInterface } from './ui-form/state';
import { DataCustomAttributeStateInterface } from './data-custom-attribute/state';
import { UiCustomAttributeStateInterface } from './ui-custom-attribute/state';
import { DataDnsStateInterface } from './data-dns/state';
import { UiDnsStateInterface } from './ui-dns/state';
import { DataEmailTemplateStateInterface } from './data-email-template/state';
import { UiEmailTemplateStateInterface } from './ui-email-template/state';
import { DataContractStateInterface } from './data-contract/state';
import { UiContractStateInterface } from './ui-contract/state';
import { DataUserStateInterface } from './data-user/state';
import { UiUploadStateInterface } from './ui-upload/state';
import { DataUploadStateInterface } from './data-upload/state';
import { DataDocumentStateInterface } from './data-document/state';
import { UiDocumentStateInterface } from './ui-document/state';
import { UiLayoutStateInterface } from './ui-layout/state';
import { DataAccountStateInterface } from './data-account/state';
import { DataRestrictionStateInterface } from './data-restriction/state';
import { DataSuggestionStateInterface } from './data-suggestion/state';
import { UiRestrictionStateInterface } from './ui-restriction/state';
import { UiSuggestionStateInterface } from './ui-suggestion/state';
import { UiEmailingStateInterface } from './ui-emailing/state';
import { DataWebsiteArticleStateInterface } from './data-website-article/state';
import { DataLeadStateInterface } from './data-lead/state';
import { DataWebsiteStateInterface } from './data-website/state';
import { UiLeadStateInterface } from './ui-lead/state';
import { DataProductionStateInterface } from './data-production/state';

export interface StateInterface {

  // Data states
  'data-runtime': DataRuntimeStateInterface;
  'data-property': DataPropertyStateInterface;
  'data-contact': DataContactStateInterface;
  'data-promotion': DataPromotionStateInterface;
  'data-searchlist': DataSearchlistStateInterface;
  'data-autocomplete': DataAutocompleteStateInterface;
  'data-matching-group': DataMatchingGroupStateInterface;
  'data-matching': DataMatchingStateInterface;
  'data-email': DataEmailStateInterface;
  'data-reporting': DataReportingStateInterface;
  'data-task': DataTaskStateInterface;
  'data-history': DataHistoryStateInterface;
  'data-sector': DataSectorStateInterface;
  'data-report': DataReportStateInterface;
  'data-marketing-expense': DataMarketingExpenseStateInterface;
  'data-portal': DataPortalStateInterface;
  'data-device': DataDeviceStateInterface;
  'data-custom-attribute': DataCustomAttributeStateInterface;
  'data-dns': DataDnsStateInterface;
  'data-email-template': DataEmailTemplateStateInterface;
  'data-contract': DataContractStateInterface;
  'data-user': DataUserStateInterface;
  'data-upload': DataUploadStateInterface;
  'data-document': DataDocumentStateInterface;
  'data-account': DataAccountStateInterface;
  'data-lead': DataLeadStateInterface;
  'data-website': DataWebsiteStateInterface;
  'data-website-article': DataWebsiteArticleStateInterface;
  'data-restriction': DataRestrictionStateInterface;
  'data-suggestion': DataSuggestionStateInterface;
  'data-production': DataProductionStateInterface;

  // UI states
  'ui-property': UiPropertyStateInterface;
  'ui-contact': UiContactStateInterface;
  'ui-promotion': UiPromotionStateInterface;
  'ui-page': UiPageStateInterface;
  'ui-form': UiFormStateInterface;
  'ui-searchlist': UiSearchlistStateInterface;
  'ui-autocomplete': UiAutocompleteStateInterface;
  'ui-matching-group': UiMatchingGroupStateInterface;
  'ui-matching': UiMatchingStateInterface;
  'ui-reporting': UiReportingStateInterface;
  'ui-user': UiUserStateInterface;
  'ui-task': UiTaskStateInterface;
  'ui-history': UiHistoryStateInterface;
  'ui-sector': UiSectorStateInterface;
  'ui-report': UiReportStateInterface;
  'ui-marketing-expense': UiMarketingExpenseStateInterface;
  'ui-email': UiEmailStateInterface;
  'ui-portal': UiPortalStateInterface;
  'ui-device': UiDeviceStateInterface;
  'ui-custom-attribute': UiCustomAttributeStateInterface;
  'ui-dns': UiDnsStateInterface;
  'ui-email-template': UiEmailTemplateStateInterface;
  'ui-contract': UiContractStateInterface;
  'ui-upload': UiUploadStateInterface;
  'ui-document': UiDocumentStateInterface;
  'ui-layout': UiLayoutStateInterface;
  'ui-restriction': UiRestrictionStateInterface;
  'ui-suggestion': UiSuggestionStateInterface;
  'ui-emailing': UiEmailingStateInterface;
  'ui-lead': UiLeadStateInterface;
}
